#!/bin/sh

# Check if the action is 'ifup' and the interface is 'wan'
if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "wan" ]; then
    DEVICE=$(ip -o route get 8.8.8.8 | cut -f 5 -d " ")
    NETDEV="$DEVICE"
    ethtool -K "$NETDEV" rx-udp-gro-forwarding on rx-gro-list off
fi